<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Description>A fluent HTTPResponseMessage builder with fully extendable API Client implementation.</Description>
		<PackageId>NotoriousClient</PackageId>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<VersionPrefix>2.0.2</VersionPrefix>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Authors>Brice SCHUMACHER</Authors>
		<RepositoryUrl>https://github.com/Notorious-Coding/Notorious-Client/</RepositoryUrl>
		<PackageIcon>icon.png</PackageIcon>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="6.0.0" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="7.0.0" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\icon.png" Pack="true" PackagePath="" Visible="False" />
		<None Include="..\README.md" Pack="true" PackagePath="" Visible="False" />
		<None Include="..\LICENSE.txt" Pack="true" PackagePath="" Visible="False" />
	</ItemGroup>

</Project>
