name: Publish NotoriousClient

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env: 
  nugetApiKey: ${{secrets.NUGET_API_KEY}}  
jobs:
  build:
    runs-on: windows-latest  
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build
      
    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test
      
    - name: Push
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
