name: Publish NotoriousClient

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env: 
  nugetApiKey: ${{secrets.NUGET_API_KEY}}
  nugetDirectory: ${{github.workspace}}/nuget
  nugetSource: 'https://api.nuget.org/v3/index.json'
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore
      run: dotnet restore NotoriousClient.sln

    - name: Build
      run: dotnet build --output ${{ env.nugetDirectory }}
      
    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test
      
    - name: Publish
      run: dotnet nuget push "${{ env.nugetDirectory }}/*.nupkg" -s ${{ env.nugetSource }} -k ${{ env.nugetApiKey }}
